# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-06 02:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 6, 2, 48, 58, 248000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='department',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='\u90e8\u95e8'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='memo',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='mobile',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='\u624b\u673a'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='name',
            field=models.CharField(default=datetime.datetime(2016, 3, 6, 2, 49, 34, 503000, tzinfo=utc), max_length=32, verbose_name='\u540d\u5b57'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='tel',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='\u5ea7\u673a'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='token',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='token'),
        ),
    ]
