# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-06 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myusers', '0002_auto_20160306_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='department',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='tel',
        ),
        migrations.AddField(
            model_name='myuser',
            name='IDcard',
            field=models.CharField(default=131044198303250311L, max_length=18, verbose_name='\u8eab\u4efd\u8bc1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='MBDA1',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='\u5bc6\u4fdd\u7b54\u6848'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='MBWT1',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='\u5bc6\u4fdd\u95ee\u9898'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='QQ',
            field=models.CharField(default='88888888', max_length=30, verbose_name='QQ\u53f7'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='\u5730\u5740'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='gender',
            field=models.CharField(choices=[('M', '\u7537'), ('F', '\u5973')], default='N', max_length=1, verbose_name='\u6027\u522b'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='phonenumber',
            field=models.CharField(default=15001065981L, max_length=11, verbose_name='\u624b\u673a\u53f7'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='retryCount',
            field=models.IntegerField(default=0, verbose_name='\u51fa\u9519\u6b21\u6570'),
        ),
    ]
