# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-06 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myusers', '0003_auto_20160306_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='MBDA1',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='MBWT1',
        ),
        migrations.AddField(
            model_name='myuser',
            name='MBDA',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='\u5bc6\u4fdd\u7b54\u6848'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='MBWT',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='\u5bc6\u4fdd\u95ee\u9898'),
        ),
    ]
